import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { FitBotWidget } from "@/components/fitbot-nextjs/index";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <FitBotWidget
          apiKey="nextjs-demo-key-123"
          apiUrl="http://localhost:3000"
          scriptUrl="http://localhost:3001/widget-dist/gymbot.min.js"
        />
      </body>
    </html>
  );
}
